source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'CompSciClubs' do
    pod 'JTAppleCalendar', '~> 7.0'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
end
