# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClubHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClubHub
  pod 'FSCalendar'
  pod 'JTAppleCalendar', '~> 7.0'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI' 
  pod 'FirebaseUI/Google'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
