# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccountSetup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccountSetup
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'FirebaseUI' 
  pod 'FirebaseUI/Google'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'AccountSetupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccountSetupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
